sudo: required
language: c
cache: ccache
os:
        - linux-ppc64le
        - linux

compiler:
  - gcc
  - clang

script:
  - uname -a
  - lscpu
  - make olddefconfig
  - make CC="ccache gcc" all -j$(nproc) -e QUIET=1 2> errors || cat errors
