sudo: required
language: c
cache: ccache
os:
        - linux-ppc64le
        - linux-arm64
        - linux-arm
        - linux

compiler:
  - gcc
  - clang

install: skip

script:
  - make olddefconfig
  - make CC="ccache gcc" all -j$(nproc)
